name: share_quiz
version: 1.1.2+7
environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.16.9'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.21.2
  hooks_riverpod: 2.6.1

  firebase_core: 4.1.0
  firebase_auth: 6.0.2
  cloud_firestore: 6.0.1
  google_sign_in: 6.2.2
  firebase_storage: 13.0.1
  tuple: 2.0.2
  firebase_crashlytics: 5.0.1
  crypto: 3.0.6
  image_picker: 1.1.2
  flutter_launcher_icons: 0.14.4
  flutter_settings_ui: 3.0.1
  state_notifier: 1.0.0
  intl: 0.19.0
  flutter_localizations:
    sdk: flutter
  rxdart: 0.28.0
  package_info_plus: 9.0.0
  share_plus: 12.0.0
  firebase_performance: 0.11.0+1
  collection: 1.18.0
  shared_preferences: 2.5.3

dev_dependencies:
  freezed_annotation: 2.4.4
  freezed: 2.5.7
  build_runner: 2.4.13
  json_serializable: 6.8.0
  import_sorter: 4.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/icon/icon.png'

flutter:
  generate: true
  uses-material-design: true
