name: share_quiz
description: A new Flutter application.
version: 1.0.0+2
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  freezed_annotation: ^0.14.1
  json_serializable: ^4.1.3
  hooks_riverpod: ^0.14.0+2

  firebase_core: ^1.1.0
  firebase_analytics: ^8.0.2
  firebase_auth: ">=1.1.2 <4.0.0"
  cloud_firestore: ^2.1.0
  google_sign_in: ^5.0.2
  firebase_storage: ^8.0.6

  tuple: ^2.0.0
  firebase_crashlytics: ^2.0.3
  crypto: ^3.0.1
  package_info: ^2.0.0
  import_sorter: ^4.5.1
  image_picker: ^0.7.4
  share: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_settings_ui: ^2.0.1

dev_dependencies:
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+3

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/icon/icon.png'

flutter:
  uses-material-design: true
