name: share_quiz
description: A new Flutter application.
version: 1.0.0+2
environment:
  sdk: 3.1.4
  flutter: 3.13.8

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.3
  hooks_riverpod: 2.4.4

  firebase_core: 2.19.0
  firebase_analytics: 10.6.0
  firebase_auth: 4.11.1
  cloud_firestore: 4.10.0
  google_sign_in: 6.1.5
  firebase_storage: 11.3.0
  tuple: 2.0.2
  firebase_crashlytics: 3.4.0
  crypto: 3.0.3
  image_picker: 1.0.4
  flutter_launcher_icons: 0.13.1
  flutter_settings_ui: 2.0.1
  state_notifier: 1.0.0
  intl: 0.18.1
  flutter_localizations:
    sdk: flutter
  rxdart: 0.27.7
  package_info_plus: 4.1.0
  share_plus: 7.2.1

dev_dependencies:
  freezed_annotation: 2.4.1
  freezed: 2.4.5
  build_runner: 2.4.6
  json_serializable: 6.7.1
  import_sorter: 4.6.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/icon/icon.png'

flutter:
  generate: true
  uses-material-design: true
