name: share_quiz
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.16.0
  freezed_annotation: ^0.14.1
  hooks_riverpod: ^0.14.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
