name: share_quiz
description: A new Flutter application.
version: 1.0.0+2
environment:
  sdk: 3.1.3
  flutter: 3.3.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: 0.20.2
  hooks_riverpod: 2.4.2

  firebase_core: 2.17.0
  firebase_analytics: 10.5.1
  firebase_auth: 4.10.1
  cloud_firestore: 4.9.3
  google_sign_in: 5.0.2
  firebase_storage: 11.2.8
  tuple: 2.0.2
  firebase_crashlytics: 3.3.7
  crypto: 3.0.3
  package_info: 2.0.0
  image_picker: 1.0.4
  share: 2.0.4
  flutter_launcher_icons: 0.13.1
  flutter_settings_ui: 2.0.1
  state_notifier: 0.7.2+1
  intl: 0.18.1

dev_dependencies:
  freezed_annotation: 2.4.1
  freezed: 2.4.3
  build_runner: 2.4.6
  json_serializable: 6.7.1
  import_sorter: 4.6.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/icon/icon.png'

flutter:
  uses-material-design: true
