name: share_quiz
description: A new Flutter application.
version: 1.0.0+2
environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ^3.3.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.18.5+1 <0.21.0"
  hooks_riverpod: ">=1.0.4 <3.0.0"

  firebase_core: ">=1.22.0 <3.0.0"
  firebase_analytics: ">=8.0.2 <11.0.0"
  firebase_auth: ">=1.1.2 <5.0.0"
  cloud_firestore: ">=2.1.0 <5.0.0"
  google_sign_in: ^5.0.2
  firebase_storage: ">=8.0.6 <12.0.0"

  tuple: ^2.0.0
  firebase_crashlytics: ">=2.0.3 <4.0.0"
  crypto: ^3.0.1
  package_info: ^2.0.0
  import_sorter: ^4.5.1
  image_picker: ">=0.8.4+11 <2.0.0"
  share: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_settings_ui: ^2.0.1
  state_notifier: ^0.7.2+1
  intl: ">=0.17.0 <0.19.0"

dev_dependencies:
  freezed_annotation: "^2.4.1"
  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/icon/icon.png'

flutter:
  uses-material-design: true
