name: 'Setup Build Environment and Build APK'
description: 'Sets up the required environment for Android build and builds APK'

inputs:
  gcloud_service_key:
    description: 'gcloud_service_key'
    required: true
  deploy_file_path:
    description: 'deploy_file_path'
    required: true
  appId:
    description: 'appId'
    required: true

runs:
  using: "composite"
  steps:
    - name: Decode Firebase Service Account Key
      run: echo "${{ inputs.google_service_secret }}" | base64 -d > service_account_key.json
      shell: bash

    # Firebase にデプロイ
    - name: Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{inputs.appId}}
        groups: testers
        file: ${{ inputs.deploy_file_path }}
        serviceCredentialsFile: service_account_key.json