name: 'Flutter Build'

runs:
  using: "composite"
  steps:
    - name: setup cache
      uses: actions/cache@v3
      with:
        path: /Users/runner/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache

    - name: Cache Flutter Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
        key: ${{ runner.OS }}-flutter-deps-${{ hashFiles('**/pubspec.lock') }}

    - name: install flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: flutter dependencies install
      run: flutter pub get
      shell: bash

    - name: flutter test
      run: flutter test
      shell: bash