name: Android Release CD

on:
  workflow_dispatch:
    branches: [ master ]
  pull_request:
    branches: [ dev ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install java 11.x
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.x'

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      - name: install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'

      - name: flutter dependencies install
        run: flutter pub get

      - name: flutter test
        run: flutter test

      - name:  Translate secrets of base64 into json
        run:
          mkdir ./android/app/src/release
          echo ${{ secrets.RELEASE_ANDROID_GOOGLE_SERVICE }} | base64 --decode > ./android/app/src/release/google-services.json

      - name: Create key.properties
        run: |
          echo ${{ secrets.RELEASE_ANDROID_KEYSTORE }} | base64 -d > ./android/app/src/release/release.jks
          echo ${{ secrets.RELEASE_KEY_PROPERTIES }} | base64 -d > ./android/release_key.properties

      - name: Build APK
        run: flutter build apk --release --build-number=$GITHUB_RUN_NUMBER

      # Firebase にデプロイ
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.RELEASE_FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: ./build/app/outputs/apk/release/app-release.apk