name: Android Release CD

on:
  push:
    branches:
      - a

concurrency:
  group: pr-${{ github.event.pull_request.number }}-Android Release CD
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          build_type: release
          google_service_secret: ${{ secrets.RELEASE_ANDROID_GOOGLE_SERVICE }}
          keystore_secret: ${{ secrets.RELEASE_ANDROID_KEYSTORE }}
          key_properties_secret: ${{ secrets.RELEASE_KEY_PROPERTIES }}

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          gcloud_service_key: ${{ secrets.RELEASE_GCLOUD_SERVICE_KEY }}
          deploy_file_path: ./build/app/outputs/bundle/release/app-release.aab
          appId: ${{secrets.RELEASE_FIREBASE_APP_ID_ANDROID}}