name: Android Dev CD

on:
  push:
    branches:
      - a

concurrency:
  group: pr-${{ github.event.pull_request.number }}-Android Dev CD
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          build_type: debug
          google_service_secret: ${{ secrets.DEBUG_ANDROID_GOOGLE_SERVICE }}
          keystore_secret: ${{ secrets.DEBUG_ANDROID_KEYSTORE }}
          key_properties_secret: ${{ secrets.DEBUG_KEY_PROPERTIES }}

      - name: Decode Firebase Service Account Key
        run: echo "${{ secrets.DEVELOP_GCLOUD_SERVICE_KEY }}" | base64 -d > service_account_key.json

      # Firebase にデプロイ
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          groups: testers
          file: ./build/app/outputs/apk/debug/app-debug.aab
          serviceCredentialsFile: service_account_key.json
