name: Android Dev CD

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install java 11.x
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.x'

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      - name: install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
          channel: 'stable'

      - name: flutter dependencies install
        run: flutter pub get

      - name: flutter test
        run: flutter test

      - name:  Translate secrets of base64 into json
        env:
          GOOGLE_SERVICE: ${{ secrets.DEBUG_ANDROID_GOOGLE_SERVICE }}
        run:
          echo $GOOGLE_SERVICE | base64 --decode > ./android/app/src/debug/google-services.json

      - name: Create key.properties
        run: |
          echo ${{ secrets.DEBUG_ANDROID_KEYSTORE }} | base64 -d > ./android/app/src/debug/debug.keystore
          echo 'store_password=${{ secrets.DEBUG_ANDROID_STORE_PASSWORD }}' >> ./android/debug_key.properties
          echo 'key_ailias=${{ secrets.DEBUG_ANDROID_AILIAS }}' >> ./android/debug_key.properties
          echo 'key_password=${{ secrets.DEBUG_ANDROID_STORE_PASSWORD }}' >> ./android/debug_key.properties

      - name: Build APK
        run: flutter build apk --debug --build-number=$GITHUB_RUN_NUMBER

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/flutter-apk/app-debug.apk

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # モジュールのダウンロード
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: android

      # Firebase にデプロイ
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: android/app-debug.apk