name: Android Dev CD

on:
  push:
    branches:
      - a

concurrency:
  group: pr-${{ github.event.pull_request.number }}-Android Dev CD
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          build_type: debug
          google_service_secret: ${{ secrets.DEBUG_ANDROID_GOOGLE_SERVICE }}
          keystore_secret: ${{ secrets.DEBUG_ANDROID_KEYSTORE }}
          key_properties_secret: ${{ secrets.DEBUG_KEY_PROPERTIES }}

      - name: deploy
        uses: ./.github/actions/deploy
        with:
          gcloud_service_key: ${{ secrets.DEVELOP_GCLOUD_SERVICE_KEY }}
          deploy_file_path: ./build/app/outputs/apk/debug/app-debug.apk
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
