name: Android Build

on:
  push:
    branches:
      - a

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          secrets_debug_android_google_service: ${{ secrets.DEBUG_ANDROID_GOOGLE_SERVICE }}
          secrets_debug_android_keystore: ${{ secrets.DEBUG_ANDROID_KEYSTORE }}
          secrets_debug_key_properties: ${{ secrets.DEBUG_KEY_PROPERTIES }}