name: Android Release CD

on:
  push:
    branches:
      - a

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install java 11.x
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.x'

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: flutter dependencies install
        run: flutter pub get

      - name: flutter test
        run: flutter test

      - name: mkdir
        run:
          mkdir ./android/app/src/release

      - name:  Translate secrets of base64 into json
        run:
          echo ${{ secrets.RELEASE_ANDROID_GOOGLE_SERVICE }} | base64 --decode > ./android/app/src/release/google-services.json

      - name: Create key.properties
        run: |
          echo ${{ secrets.RELEASE_ANDROID_KEYSTORE }} | base64 -d > ./android/app/src/release/release.jks
          echo ${{ secrets.RELEASE_KEY_PROPERTIES }} | base64 -d > ./android/release_key.properties

      - name: Build APK
        run: flutter build appbundle --release --build-number=$GITHUB_RUN_NUMBER

      - name: Set up Google Cloud authentication
        run: |
          # DEVELOP_GCLOUD_SERVICE_KEYをデコードして/tmp/credentials.jsonに保存
          echo "${{ secrets.DEVELOP_GCLOUD_SERVICE_KEY }}" | base64 -d > /tmp/credentials.json

          # GOOGLE_APPLICATION_CREDENTIALS環境変数にパスをセット
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json" >> $GITHUB_ENV

      # Firebase にデプロイ
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.RELEASE_FIREBASE_APP_ID_ANDROID}}
          groups: testers
          file: ./build/app/outputs/bundle/release/app-release.aab