name: Android Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'dev'

concurrency:
  group: pr-${{ github.event.pull_request.number }}-Android Build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          build_type: debug
          google_service_secret: ${{ secrets.DEBUG_ANDROID_GOOGLE_SERVICE }}
          keystore_secret: ${{ secrets.DEBUG_ANDROID_KEYSTORE }}
          key_properties_secret: ${{ secrets.DEBUG_KEY_PROPERTIES }}