name: Android Build

on:
  push:
    branches:
      - a

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          build_type: debug
          google_service_secret: ${{ secrets.DEBUG_ANDROID_GOOGLE_SERVICE }}
          keystore_secret: ${{ secrets.DEBUG_ANDROID_KEYSTORE }}
          key_properties_secret: ${{ secrets.DEBUG_KEY_PROPERTIES }}