name: Android Dev CD

on:
  push:
    branches:
      - a

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          secrets_debug_android_google_service: ${{ secrets.DEBUG_ANDROID_GOOGLE_SERVICE }}
          secrets_debug_android_keystore: ${{ secrets.DEBUG_ANDROID_KEYSTORE }}
          secrets_debug_key_properties: ${{ secrets.DEBUG_KEY_PROPERTIES }}

      - name: Set up Google Cloud authentication
        run: |
          # DEVELOP_GCLOUD_SERVICE_KEYをデコードして/tmp/credentials.jsonに保存
          echo "${{ secrets.DEVELOP_GCLOUD_SERVICE_KEY }}" | base64 -d > /tmp/credentials.json

          # GOOGLE_APPLICATION_CREDENTIALS環境変数にパスをセット
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/credentials.json" >> $GITHUB_ENV

      # Firebase にデプロイ
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          groups: testers
          file: ./build/app/outputs/apk/debug/app-debug.apk