name: Android Dev CD

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          secrets_debug_android_google_service: ${{ secrets.DEBUG_ANDROID_GOOGLE_SERVICE }}
          secrets_debug_android_keystore: ${{ secrets.DEBUG_ANDROID_KEYSTORE }}
          secrets_debug_key_properties: ${{ secrets.DEBUG_KEY_PROPERTIES }}

      # Firebase にデプロイ
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: ./build/app/outputs/apk/debug/app-debug.apk